name: Publish Package
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - run: pnpm install
      - run: pnpm build
      - run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm publish
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
